Preheader: {shape: circle}
Header: {shape: circle}
BB1: {shape: circle}
BB2: {shape: circle}
BB3: {shape: circle}
Outside loop: {shape: circle}

Preheader -> Header
Header -> BB1
Header -> BB2
Header -> BB3
BB2 -> Outside loop
